### ISSUE TITLE
getFactors() Error

### ISSUE THREAD

**Issue by lewisstancer** [onelogin/onelogin-php-sdk#18]
The following error is displayed when attempting to getFactors for a User ID

`Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, stdClass given in /var/www/test/vendor/onelogin/api/src/OneLoginClient.php:226 Stack trace: #0 /var/www/test/vendor/onelogin/api/src/OneLoginClient.php(226): count() #1 /var/www/test/vendor/onelogin/api/src/OneLoginClient.php(2072): OneLogin\api\OneLoginClient->handleDataResponse() #2 /var/www/test/admin/debug.php(31): OneLogin\api\OneLoginClient->getFactors() #3 {main} thrown in /var/www/test/vendor/onelogin/api/src/OneLoginClient.php on line 226`

PHP Code:
```
$client = new OneLoginClient($clientId, $clientSecret, $region);
$authFactors = $client->getFactors(77149912);
```

**Comment by Subterrane** [comment]
This `count(): Argument #1 must be of type Countable|array, stdClass given` crash is **fixed**. Commit e4a1230 ("Fix handleDataResponse and model constructors for otp_devices API compatibility") added an `is_array($data)` guard before the `count()` call in `handleDataResponse()`. The fix shipped in **v1.8.0**.

Please upgrade via Composer to `^1.8.0` and `getFactors()` will work. Closing as resolved.
